import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
<<<<<<< HEAD
<<<<<<< HEAD
=======
import Providers from './providers';
import Link from 'next/link';
import ThemeSwitcher from '@/components/ThemeSwitcher';
>>>>>>> f418b28 (Switch funcionando)
=======
import Providers from './providers';
import Navbar from '@/components/NavBar';
import Footer from '@/components/Footer';
>>>>>>> develop

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
<<<<<<< HEAD
      <body className={inter.className}>{children}</body>
=======
      <body className={`${inter.className} flex min-h-screen flex-col`}>
        <Providers>
          <header className='fixed w-screen z-50'>
            <Navbar />
          </header>
          {children}
          <footer>
            <Footer />
          </footer>
        </Providers>
      </body>
>>>>>>> develop
    </html>
  );
}
