import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Providers from './providers';
import Link from 'next/link';
import ThemeSwitcher from '@/components/ThemeSwitcher';
import Image from 'next/image';
import Navbar from '@/components/NavBar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={`${inter.className} `}>
        <Providers>
          <header className='fixed w-screen'>
            <nav>
              <Navbar />
            </nav>
          </header>
          {children}
          <footer></footer>
        </Providers>
      </body>
    </html>
  );
}
